version: '3.1'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    env_file:
      - db.env
    ports:
      - 3306:3306
    volumes:
      - /var/docker/mariadb:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
